### ISSUE TITLE
Build crashed

### ISSUE THREAD

**Issue by boogheta** [medialab/website#523]
@AmelieVRL clicked on the build button to push changes to prod at 11:00 this morning and the backoffice stayed stuck staying "Le site est en train de builder"

Looking at the backoffice logs, we can see this stack happenned then:
```
Building site...
(node:42) UnhandledPromiseRejectionWarning: NotFoundGraphError: Graph.getNodeAttributes: could not find the "202228bf-97eb-4f98-bc28-8ac7462e09e5" node in the graph.
at Graph.getNodeAttributes (/website/node_modules/graphology/src/graph.js:1571:13)
at Database.homeSettings.slider.homeSettings.slider.map.item (/website/wilson/database.js:177:25)
at Array.map (<anonymous>)
at new Database (/website/wilson/database.js:176:47)
at Function.Database.fromDisk (/website/wilson/database.js:331:10)
at build (/website/wilson/index.js:258:23)
at building (/website/api/server.js:571:16)
at eachfn (/website/node_modules/async/dist/async.js:2948:28)
at replenish (/website/node_modules/async/dist/async.js:440:21)
at iterateeCallback (/website/node_modules/async/dist/async.js:424:21)
(node:42) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:42) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by boogheta** [comment]
I restarted the website_api container from rancher, tried to save some news and clicked on build again, it did build without any issue this time. Not sure what was the problem and how it fixed itself on its own :/ 

On a side note, when build works properly, I noticed a difference between:
- automated ones (from cronjobs) properly announce completion:
```
15:00:00 Building site...
15:02: build: 104634.613ms
15:02: Done building site.
```
- while manual ones (from the backoffice button) conclude by saying just "null":
```
14:49:02 Building site...
14:51:16 build: 133523.259ms
14:51:17 null
```
